const productData = [
  {   
    id: 300, 
    nombre:"GFORCE RTX 3080",
    descripcion:"TARJETA GRÁFICA ENVIDIA",
    especificaciones:"MEMORIA DE 16GB",
    imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
    nroserie:"32165488752",
    nromac:"ABC-1235-1215-4545",
    precio: 3500,
    stock: 35,
    minimo: 10,
    preferencia: 1,
    estado: true,
    idCategoria: 3,
    idMarca: 3,
    idFabricante: 1,
    rating: 5
    },
    {   
      id: 301, 
      nombre:"GFORCE RTX 3080",
      descripcion:"TARJETA GRÁFICA ENVIDIA",
      especificaciones:"MEMORIA DE 16GB",
      imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
      nroserie:"32165488752",
      nromac:"ABC-1235-1215-4545",
      precio: 3500,
      stock: 35,
      minimo: 10,
      preferencia: 1,
      estado: true,
      idCategoria: 3,
      idMarca: 3,
      idFabricante: 1,
      rating: 7
      },
      {   
        id: 302, 
        nombre:"GFORCE RTX 3080",
        descripcion:"TARJETA GRÁFICA ENVIDIA",
        especificaciones:"MEMORIA DE 16GB",
        imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
        nroserie:"32165488752",
        nromac:"ABC-1235-1215-4545",
        precio: 3500,
        stock: 35,
        minimo: 10,
        preferencia: 1,
        estado: true,
        idCategoria: 3,
        idMarca: 3,
        idFabricante: 1,
        rating: 2
        },
        {   
          id: 303, 
          nombre:"GFORCE RTX 3080",
          descripcion:"TARJETA GRÁFICA ENVIDIA",
          especificaciones:"MEMORIA DE 16GB",
          imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
          nroserie:"32165488752",
          nromac:"ABC-1235-1215-4545",
          precio: 3500,
          stock: 35,
          minimo: 10,
          preferencia: 1,
          estado: true,
          idCategoria: 3,
          idMarca: 3,
          idFabricante: 1,
          rating: 1
          },
          {   
            id: 304, 
            nombre:"GFORCE RTX 3080",
            descripcion:"TARJETA GRÁFICA ENVIDIA",
            especificaciones:"MEMORIA DE 16GB",
            imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
            nroserie:"32165488752",
            nromac:"ABC-1235-1215-4545",
            precio: 3500,
            stock: 35,
            minimo: 10,
            preferencia: 1,
            estado: true,
            idCategoria: 3,
            idMarca: 3,
            idFabricante: 1,
            rating: 10
            },
            {  
              id: 305, 
              nombre:"GFORCE RTX 3080",
              descripcion:"TARJETA GRÁFICA ENVIDIA",
              especificaciones:"MEMORIA DE 16GB",
              imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
              nroserie: "32165488752",
              nromac:"ABC-1235-1215-4545",
              precio:3500,
              stock: 35,
              minimo: 10,
              preferencia: 1,
              estado: true,
              idCategoria: 3,
              idMarca: 3,
              idFabricante: 1,
              rating: 8
              },
];
export default productData;